# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_3b

ir:
  subnet_config_path: /work/hdd/bcha/syu2/llama3_2/Llama-3.2-3B-Instruct-hf/OSF-random-new/llama_32_3b_sampled_configs.pth

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /work/hdd/bcha/syu2/llama3_2/Llama-3.2-3B-Instruct-hf/OSF-random-new/
  checkpoint_files: [
      #  model-00001-of-00002.safetensors,
      hf_model_0001_0.pt,
      hf_model_0002_0.pt,
      #  model-00002-of-00002.safetensors,
    ]
  output_dir: /work/hdd/bcha/syu2/llama3_2/Llama-3.2-3B-Instruct-hf/OSF-random-new/
  model_type: LLAMA3_2

# Tokenizer
tokenizer:
  _component_:  torchtune.models.llama3.llama3_tokenizer
  path: /work/hdd/bcha/syu2/llama3_2/Llama-3.2-3B-Instruct-hf/original/tokenizer.model
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2","commonsense_qa","hellaswag"]
limit: null
max_seq_length: 4096
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null
